#!/usr/bin/env bash
# Simple orchestrator placeholder: read tmp/ and call LLM to generate specs into specs/
# IMPORTANT: implement your provider's API call here (OpenAI / Anthropic / local model).
# Usage: ./scripts/ai-orchestrator.sh tmp specs
set -euo pipefail
TMP_DIR="${1:-tmp}"
OUT_DIR="${2:-specs}"
mkdir -p "$OUT_DIR"

echo "Orchestrator: reading $TMP_DIR"

# If OPENAI_API_KEY is present, attempt a minimal generation via OpenAI Chat Completions API.
if [ -n "${OPENAI_API_KEY:-}" ]; then
  echo "OPENAI_API_KEY detected — running a minimal generation (conservative)."
  PROMPT="Generate a single feature spec markdown file using this template:\n\n---\ntitle: \"Auto: Example feature\"\nslug: \"auto-example-feature\"\nsummary: \"An example generated feature\"\nowner: \"docs-bot\"\ntags:\n  - auto-generated\nconfidence: 0.5\n---\n\n## Description\nA placeholder feature autogenerated by the pipeline.\n\n## Acceptance criteria\n- [ ] Example criterion\n\n## Evidence\n- tmp/README.md\n"

  RESPONSE=$(curl -sS https://api.openai.com/v1/chat/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${OPENAI_API_KEY}" \
    -d "{\"model\": \"gpt-4o-mini\", \"messages\": [{\"role\": \"user\", \"content\": \"${PROMPT}\"}], \"max_tokens\": 800, \"temperature\": 0.0}") || true

  SPEC_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content' 2>/dev/null || true)
  if [ -n "$SPEC_CONTENT" ]; then
    echo "$SPEC_CONTENT" > "$OUT_DIR/ai-generated-spec.md"
    echo "Wrote $OUT_DIR/ai-generated-spec.md"
  else
    echo "LLM call returned no content; writing placeholder spec instead."
    cat > "$OUT_DIR/placeholder-spec.md" <<'EOF'
---
title: "Placeholder: Example feature"
slug: "example-feature"
summary: "An example auto-generated feature to validate the pipeline."
owner: "docs-team"
tags:
  - "auto-generated"
evidence:
  - path: "tmp/README.md"
    excerpt: "README content"
confidence: 0.5
---

## Description
This placeholder spec demonstrates the repo pipeline.

## Acceptance criteria
- [ ] Placeholder criterion

## Related code
- tmp/README.md
EOF
  fi
else
  echo "OPENAI_API_KEY not set — writing placeholder spec only."
  cat > "$OUT_DIR/placeholder-spec.md" <<'EOF'
---
title: "Placeholder: Example feature"
slug: "example-feature"
summary: "An example auto-generated feature to validate the pipeline."
owner: "docs-team"
tags:
  - "auto-generated"
evidence:
  - path: "tmp/README.md"
    excerpt: "README content"
confidence: 0.5
---

## Description
This placeholder spec demonstrates the repo pipeline.

## Acceptance criteria
- [ ] Placeholder criterion

## Related code
- tmp/README.md
EOF
fi

echo "Orchestrator finished. Review $OUT_DIR"
